Args = --initialize-at-build-time=org.bouncycastle,scala.cli.signing.internal.BCInitializer \
       --initialize-at-run-time=org.bouncycastle.jcajce.provider.drbg.DRBG$Default,org.bouncycastle.jcajce.provider.drbg.DRBG$NonceAndIV
