#!/usr/bin/env bash
set -e

# This script ensures:
# - that we're using the right JVM (currently, temurin:17)
# - that we run the mill launcher script with bash rather than sh,
#   as the latter has issues with '+' characters, that can appear
#   in the JVM entry put in PATH by 'cs'.

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

if ! command -v cs >/dev/null; then
  cat 1>&2 << EOF
cs command not found.

Please download a cs launcher from
  https://github.com/coursier/coursier/releases/tag/v2.1.0-M2
and install it as 'cs' in your PATH.
EOF
  exit 1
fi

eval "$(cs java --env --jvm temurin:17 || cs java --env --jvm openjdk:1.17.0)"

exec /usr/bin/env bash "$DIR/millw" "$@"
