name: CI
on:
  push:
    branches:
    - main
    - m1-test
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  native-tests:
    timeout-minutes: 240
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["macOS-m1"]
        jvm: ["https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-darwin-aarch64-22.1.0.tar.gz"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@f883d08305acbc28e5e5363bf5ec086397627021
      with:
        apps: ""
        jvm: ${{ matrix.jvm }}
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Generate native launcher
      run: .github/scripts/generate-native-image.sh
      shell: bash
    - run: ./mill -i ci.setShouldPublish
    - name: Copy artifacts
      run: ./mill -i copyDefaultLauncher artifacts/
    - uses: actions/upload-artifact@v3
      with:
        name: launchers
        path: artifacts/  
        if-no-files-found: error
        retention-days: 2
    - name: Native integration tests
      run: ./mill -i nativeIntegrationTests  
      env:
        COURSIER_JNI: force   
        UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
