name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  changes:
    uses: ./.github/workflows/changes.yml

  jvm:
    needs: [changes]
    uses: ./.github/workflows/jvm.yml
    secrets: inherit
    with:
      code: ${{ needs.changes.outputs.code }}
      ci: ${{ needs.changes.outputs.ci }}
      mill_wrapper: ${{ needs.changes.outputs.mill_wrapper }}
      test_all: ${{ needs.changes.outputs.test_all }}
      test_integration: ${{ needs.changes.outputs.test_integration }}
      test_skip: ${{ needs.changes.outputs.test_skip }}

  linux:
    needs: [changes]
    uses: ./.github/workflows/linux.yml
    secrets: inherit
    with:
      code: ${{ needs.changes.outputs.code }}
      ci: ${{ needs.changes.outputs.ci }}
      mill_wrapper: ${{ needs.changes.outputs.mill_wrapper }}
      test_all: ${{ needs.changes.outputs.test_all }}
      test_native: ${{ needs.changes.outputs.test_native }}
      test_skip: ${{ needs.changes.outputs.test_skip }}

  macos:
    needs: [changes]
    uses: ./.github/workflows/macos.yml
    secrets: inherit
    with:
      code: ${{ needs.changes.outputs.code }}
      ci: ${{ needs.changes.outputs.ci }}
      mill_wrapper: ${{ needs.changes.outputs.mill_wrapper }}
      test_all: ${{ needs.changes.outputs.test_all }}
      test_native: ${{ needs.changes.outputs.test_native }}
      test_skip: ${{ needs.changes.outputs.test_skip }}

  windows:
    needs: [changes]
    uses: ./.github/workflows/windows.yml
    secrets: inherit
    with:
      code: ${{ needs.changes.outputs.code }}
      ci: ${{ needs.changes.outputs.ci }}
      mill_wrapper: ${{ needs.changes.outputs.mill_wrapper }}
      test_all: ${{ needs.changes.outputs.test_all }}
      test_native: ${{ needs.changes.outputs.test_native }}
      test_skip: ${{ needs.changes.outputs.test_skip }}

  static:
    needs: [changes]
    uses: ./.github/workflows/static.yml
    secrets: inherit
    with:
      code: ${{ needs.changes.outputs.code }}
      ci: ${{ needs.changes.outputs.ci }}
      mill_wrapper: ${{ needs.changes.outputs.mill_wrapper }}
      test_all: ${{ needs.changes.outputs.test_all }}
      test_native: ${{ needs.changes.outputs.test_native }}
      test_skip: ${{ needs.changes.outputs.test_skip }}

  mostly-static:
    needs: [changes]
    uses: ./.github/workflows/mostly-static.yml
    secrets: inherit
    with:
      code: ${{ needs.changes.outputs.code }}
      ci: ${{ needs.changes.outputs.ci }}
      mill_wrapper: ${{ needs.changes.outputs.mill_wrapper }}
      test_all: ${{ needs.changes.outputs.test_all }}
      test_native: ${{ needs.changes.outputs.test_native }}
      test_skip: ${{ needs.changes.outputs.test_skip }}

  misc:
    needs: [changes]
    uses: ./.github/workflows/misc.yml
    secrets: inherit
    with:
      code: ${{ needs.changes.outputs.code }}
      docs: ${{ needs.changes.outputs.docs }}
      ci: ${{ needs.changes.outputs.ci }}
      format_config: ${{ needs.changes.outputs.format_config }}
      benchmark: ${{ needs.changes.outputs.benchmark }}
      gifs: ${{ needs.changes.outputs.gifs }}
      mill_wrapper: ${{ needs.changes.outputs.mill_wrapper }}
      test_all: ${{ needs.changes.outputs.test_all }}
      test_docs: ${{ needs.changes.outputs.test_docs }}
      test_format: ${{ needs.changes.outputs.test_format }}
      test_skip: ${{ needs.changes.outputs.test_skip }}

  release:
    needs: [changes, jvm, linux, macos, windows, static, mostly-static, misc]
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
