name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  actions: write
jobs:
  report:
    runs-on: ubuntu-24.04
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: /test-results-(.*)/
          name: 'Test report $1'
          path: '*.xml'
          reporter: java-junit